# Generated by Django 2.2.8 on 2022-12-26 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20221213_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='hotels.Hotel'),
        ),
        migrations.DeleteModel(
            name='Hotel',
        ),
    ]
